import { GridColDef } from '@mui/x-data-grid';
//import { DatosPacc } from './datos'; 


//export const columnsPacc: GridColDef<DatosPacc>[] = [
  export const columnsPacc: GridColDef[] = [
    {
      field: 'codigoSistema',
      headerName: 'CÓDIGO DE CATALOGO',
      width: 180,
      editable: false,
      headerClassName: 'custom-header',
      headerAlign: 'center',
      align: 'center',
    },
    {
      field: 'gerenciaDepartamento',
      headerName: 'GERENCIA O DEPARTAMENTO',
      width: 220,
      editable: false,
      headerClassName: 'custom-header',
      headerAlign: 'center',
      align: 'center',
    },
    {
      field: 'cuentaObjetal',
      headerName: 'CUENTA OBJETAL',
      width: 220,
      editable: false,
      headerClassName: 'custom-header',
      headerAlign: 'center',
      align: 'center',
    },
    {
      field: 'descripcion',
      headerName: 'DESCRIPCIÓN',
      width: 580,
      editable: false,
      headerClassName: 'custom-header',
      headerAlign: 'left',
      align: 'left',
    },
    {
      field: 'unidadMedida',
      headerName: 'UNIDAD DE MEDIDA',
      width: 180,
      editable: false,
      headerClassName: 'custom-header',
      headerAlign: 'center',
      align: 'center',
    },
    {
      field: 'precioUnitario',
      headerName: 'PRECIO UNITARIO',
      width: 180,
      editable: false,
      headerClassName: 'custom-header',
      headerAlign: 'center',
      align: 'center',
      type: 'number',
    },
    {
      field: 'trimestre',
      headerName: 'TRIMESTRE',
      width: 180,
      editable: false,
      headerClassName: 'custom-header',
      headerAlign: 'center',
      align: 'center',
    },
    {
      field: 'total', // Campo total
      headerName: 'TOTAL',
      width: 180,
      editable: false,
      headerClassName: 'custom-header',
      headerAlign: 'center',
      align: 'center',
      type: 'number',
    },
  ];
  export const columnsCatalogo: GridColDef[] = [
    {
      field: 'codigoSistema',
      headerName: 'CODIGO SISTEMA',
      width: 280,
      editable: false,
      headerClassName: 'custom-header',
      headerAlign: 'center',
      align: 'center',
    },
    {
      field: 'descripcion',
      headerName: 'DESCRIPCIÓN',
      width: 580,
      editable: false,
      headerClassName: 'custom-header',
      headerAlign: 'center',
      align: 'left',
    },
  ];

export const columnsObras: GridColDef[] = [
  {
    field: 'codigoSistema',
    headerName: 'CODIGO SISTEMA',
    width: 180,
    editable: true,
    headerClassName: 'custom-header',
    headerAlign: 'center',
    align: 'center',
  },
  {
    field: 'cuentaObjetal',
    headerName: 'CUENTA OBJETAL',
    width: 280,
    editable: true,
    headerClassName: 'custom-header',
    headerAlign: 'center',
    align: 'center',
  },
  {
    field: 'descripcion',
    headerName: 'DESCRIPCIÓN',
    width: 580,
    editable: true,
    headerClassName: 'custom-header',
    headerAlign: 'left',
    align: 'left',
  },
  {
    field: 'cantidad',
    headerName: 'CANTIDAD',
    width: 280,
    editable: true,
    headerClassName: 'custom-header',
    headerAlign: 'center',
    type: 'number',
    align: 'center',
  },
  {
    field: 'borrarBoton',
    headerName: '',
    width: 120,
    editable: false,
    headerAlign: 'center',
    align: 'center',
  },
];

export const newColumns: GridColDef[] = [
  {
    field: 'codigoSistema',
    headerName: 'CODIGO SISTEMA',
    width: 180,
    editable: true,
    headerClassName: 'custom-header',
    headerAlign: 'center',
    align: 'center',
  },
  {
    field: 'cuentaObjetal',
    headerName: 'CUENTA OBJETAL',
    width: 180,
    editable: true,
    headerClassName: 'custom-header',
    headerAlign: 'center',
    align: 'center',
  },
  {
    field: 'descripcion',
    headerName: 'DESCRIPCIÓN',
    width: 380,
    editable: true,
    headerClassName: 'custom-header',
    headerAlign: 'left',
    align: 'left',
  },
  {
    field: 'inv',
    headerName: 'INV',
    width: 100,
    editable: true,
    headerClassName: 'custom-header',
    headerAlign: 'center',
    align: 'center',
  },
  {
    field: 'medida',
    headerName: 'MEDIDA',
    width: 120,
    editable: true,
    headerClassName: 'custom-header',
    headerAlign: 'center',
    align: 'center',
    type: "singleSelect",
    valueOptions: ["Unidad", "Caja", "Paquetes", "Par"]
  },
  {
    field: 'cantidad',
    headerName: 'CANTIDAD',
    width: 120,
    editable: true,
    headerClassName: 'custom-header',
    headerAlign: 'center',
    type: 'number',
    align: 'center',
  },
  {
    field: 'borrarBoton',
    headerName: '',
    width: 120,
    editable: false,
    headerAlign: 'center',
    align: 'center',
  },
];